"""Deterministic and overwrite-safe plugin scaffolding tests."""

from __future__ import annotations

import contextlib
import io
import os
import subprocess
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

from harness.plugins import load_manifest
from harness.scaffold import PluginKind, create_plugin, validate_plugin
from harness.scaffold.cli import main


class PluginScaffoldTests(unittest.TestCase):
    """Exercise every built-in layout and filesystem failure mode."""

    def setUp(self) -> None:
        self.temporary = tempfile.TemporaryDirectory()
        self.root = Path(self.temporary.name)

    def tearDown(self) -> None:
        self.temporary.cleanup()

    def _tree(self, root: Path) -> dict[str, bytes]:
        return {
            path.relative_to(root).as_posix(): path.read_bytes()
            for path in sorted(item for item in root.rglob("*") if item.is_file())
        }

    def test_all_contribution_forms_have_exact_manifest_authority(self) -> None:
        """Generated manifests declare only the contribution form requested."""
        for kind in PluginKind:
            with self.subTest(kind=kind.value):
                root = create_plugin(
                    kind,
                    f"com.example.{kind.value}",
                    self.root / kind.value,
                )
                manifest_text = (root / "plugin.toml").read_text(encoding="utf-8")
                self.assertEqual(manifest_text.count("com.example."), 1)
                self.assertNotIn("revision", manifest_text.lower())
                self.assertEqual((root / "pyproject.toml").exists(), kind is not PluginKind.CLIENT)
                self.assertEqual((root / "frontend").exists(), kind is not PluginKind.BACKEND)
                self.assertEqual(
                    (root / "protocol/api.schema.json").exists(),
                    kind is PluginKind.FULL_STACK,
                )
                if kind is PluginKind.BACKEND:
                    self.assertIs(validate_plugin(root), kind)
                else:
                    with self.assertRaisesRegex(ValueError, "pnpm --dir frontend run build"):
                        validate_plugin(root)
                    bundle = root / "frontend/dist/client.js"
                    bundle.parent.mkdir()
                    bundle.write_text("export default () => undefined\n", encoding="utf-8")
                    self.assertIs(validate_plugin(root), kind)
                loaded = load_manifest(root)
                self.assertEqual(loaded.manifest.plugin_id, f"com.example.{kind.value}")

    def test_generation_is_byte_deterministic_across_destination_spellings(self) -> None:
        """Absolute and relative destinations do not enter generated bytes."""
        first = create_plugin(
            PluginKind.FULL_STACK,
            "com.example.echo",
            self.root / "first",
        )
        current = Path.cwd()
        try:
            os.chdir(self.root)
            second = create_plugin(
                PluginKind.FULL_STACK,
                "com.example.echo",
                Path("second"),
            )
        finally:
            os.chdir(current)
        self.assertEqual(self._tree(first), self._tree(second))

    def test_existing_directory_file_and_symlink_are_never_replaced(self) -> None:
        """Every kind of existing destination remains byte-for-byte user-owned."""
        directory = self.root / "directory"
        directory.mkdir()
        marker = directory / "marker"
        marker.write_text("keep", encoding="utf-8")
        file = self.root / "file"
        file.write_text("keep-file", encoding="utf-8")
        link = self.root / "link"
        link.symlink_to(file)

        for destination in (directory, file, link):
            with self.subTest(destination=destination.name), self.assertRaises(FileExistsError):
                create_plugin(
                    PluginKind.BACKEND,
                    "com.example.safe",
                    destination,
                )
        self.assertEqual(marker.read_text(encoding="utf-8"), "keep")
        self.assertEqual(file.read_text(encoding="utf-8"), "keep-file")
        self.assertTrue(link.is_symlink())

    def test_render_failure_removes_only_generator_owned_temporary_tree(self) -> None:
        """A failed source validation leaves no destination or partial sibling."""
        destination = self.root / "failed"
        with (
            patch(
                "harness.scaffold.generator._validate_source_tree",
                side_effect=RuntimeError("render failed"),
            ),
            self.assertRaisesRegex(RuntimeError, "render failed"),
        ):
            create_plugin(
                PluginKind.BACKEND,
                "com.example.failed",
                destination,
            )
        self.assertFalse(destination.exists())
        self.assertEqual(tuple(self.root.iterdir()), ())

    def test_invalid_inputs_fail_before_writing(self) -> None:
        """Identity, version, parent, and destination checks precede rendering."""
        cases = (
            ("invalid", "0.1.0", self.root / "invalid-id"),
            ("com.example.valid", "next", self.root / "invalid-version"),
            ("com.example.valid", "0.1.0", self.root / "missing" / "plugin"),
        )
        for plugin_id, version, destination in cases:
            with self.subTest(destination=destination), self.assertRaises((OSError, ValueError)):
                create_plugin(
                    PluginKind.BACKEND,
                    plugin_id,
                    destination,
                    version=version,
                )
        self.assertEqual(tuple(self.root.iterdir()), ())

    def test_cli_create_and_validate_share_the_public_implementation(self) -> None:
        """Script arguments create and validate the same backend project."""
        destination = self.root / "cli"
        output = io.StringIO()
        with contextlib.redirect_stdout(output):
            status = main(
                [
                    "create",
                    "--kind",
                    "backend",
                    "--plugin-id",
                    "com.example.cli",
                    "--destination",
                    str(destination),
                ]
            )
        self.assertEqual(status, 0)
        self.assertEqual(Path(output.getvalue().strip()), destination.resolve())

        output = io.StringIO()
        with contextlib.redirect_stdout(output):
            status = main(["validate", str(destination)])
        self.assertEqual(status, 0)
        self.assertEqual(Path(output.getvalue().strip()), destination.resolve())

    def test_generated_backend_tests_use_the_public_lifecycle_harness(self) -> None:
        """Backend and full-stack fixtures execute without private registry access."""
        for kind in (PluginKind.BACKEND, PluginKind.FULL_STACK):
            with self.subTest(kind=kind.value):
                root = create_plugin(
                    kind,
                    f"com.example.{kind.value}",
                    self.root / kind.value,
                )
                completed = subprocess.run(
                    ["python", "-m", "unittest", "discover", "-s", "tests", "-v"],
                    cwd=root,
                    check=False,
                    capture_output=True,
                    text=True,
                )
                self.assertEqual(completed.returncode, 0, completed.stderr)

    def test_generated_frontends_typecheck_test_build_and_validate(self) -> None:
        """Client templates consume the workspace SDK as downstream projects."""
        project = Path(__file__).resolve().parents[1]
        frontend = project / "frontend"
        subprocess.run(
            ["pnpm", "--dir", "frontend", "run", "build:library"],
            cwd=project,
            check=True,
            capture_output=True,
            text=True,
        )
        binaries = frontend / "node_modules/.bin"
        for kind in (PluginKind.CLIENT, PluginKind.FULL_STACK):
            with self.subTest(kind=kind.value):
                root = create_plugin(
                    kind,
                    f"com.example.{kind.value}",
                    self.root / kind.value,
                )
                modules = root / "frontend/node_modules"
                package_scope = modules / "@deepseek-harness"
                package_scope.mkdir(parents=True)
                (package_scope / "browser-bridge-client").symlink_to(frontend)
                (modules / "vitest").symlink_to(frontend / "node_modules/vitest")
                commands = (
                    [str(binaries / "tsc"), "-p", str(root / "frontend/tsconfig.json")],
                    [
                        str(binaries / "vitest"),
                        "run",
                        "--root",
                        str(root / "frontend"),
                    ],
                    [
                        str(binaries / "esbuild"),
                        str(root / "frontend/src/plugin.ts"),
                        "--bundle",
                        "--format=esm",
                        "--platform=browser",
                        f"--outfile={root / 'frontend/dist/client.js'}",
                    ],
                )
                for command in commands:
                    completed = subprocess.run(
                        command,
                        cwd=root,
                        check=False,
                        capture_output=True,
                        text=True,
                    )
                    self.assertEqual(completed.returncode, 0, completed.stderr)
                first_bundle = (root / "frontend/dist/client.js").read_bytes()
                subprocess.run(commands[-1], cwd=root, check=True, capture_output=True)
                self.assertEqual(
                    (root / "frontend/dist/client.js").read_bytes(),
                    first_bundle,
                )
                self.assertIs(validate_plugin(root), kind)


if __name__ == "__main__":
    unittest.main()
